### ISSUE TITLE
NEAT prescriptor sample failing

### ISSUE THREAD

**Issue by dsargent** [leaf-ai/covid-xprize#169]
```
❯ python train_prescriptor.py      
/home/darren.sargent/venv/covid-xprize/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Loading historical data...
sys:1: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
Nets will be evaluated on the following geos: ['United States__nan', 'Brazil__nan', 'India__nan', 'Russia__nan', 'Brazil__Sao Paulo', 'United States__California', 'South Africa__nan', 'United States__Florida', 'United States__Texas', 'Mexico__nan']

 ****** Running generation 0 ****** 

Traceback (most recent call last):
  File "train_prescriptor.py", line 208, in <module>
    winner = p.run(eval_genomes)
  File "/home/darren.sargent/venv/covid-xprize/lib/python3.7/site-packages/neat/population.py", line 89, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "train_prescriptor.py", line 84, in eval_genomes
    cost_arr = np.array(costs[IP_COLS])[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by dsargent** [comment]
Fixed
